baseURL: "https://rkwrites.netlify.app/"
languageCode: en-us
title: RK Writes
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger !! I am Raiyan"
    Content: >
      Welcome to my blog

       * Here you'll find a lot of cool information about a lot of cool stuff.

       * Opinions are of my own

  socialIcons:
    - name: portfolio
      url: "https://kraiyan.github.io"
    - name: medium
      url: "https://medium.com/@kraiyan466"
    - name: twitter
      url: "https://x.com/khanraiyan14"
    - name: github
      url: "https://github.com/kraiyan"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 30
